### ISSUE TITLE
Can't add multiple secrets to the same KMS string 

### ISSUE THREAD

**Issue by mzuniga84** [SC5/serverless-kms-secrets#11]
I can add the first secret with no issues:

> sls encrypt -n DB:USERNAME -v testUser

But when trying to add the second one:

> sls encrypt -n DB:PASSWORD -v testPass

I get the following error:

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'decrypt' of undefined.

Thank you

**Comment by mpuittinen** [comment]
@mzuniga84 Fixed in version 1.0.2. Thanks for the feedback!
