### ISSUE TITLE
sls encrypt -n MY_VARIABLE -v 1020key -k ************ - issue

### ISSUE THREAD

**Issue by firojasha** [SC5/serverless-kms-secrets#14]
sls encrypt -n MY_VARIABLE -v 1020key -k ************

I am getting the below error while ruuning encrpt  command as above, please check once..

Select-String : A positional parameter cannot be found that accepts argument 'xoxp-1234567890-1234567890-123467890-a12346'.
At line:1 char:1
+ sls encrypt -n SECRETS:SLACK_API_TOKEN -v xoxp-1234567890-1234567890- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Select-String], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SelectStringCommand

**Comment by mpuittinen** [comment]
Hi! Can you please provide module versions (serverless, serverless-kms-secrets)? I assume from the error that you are using it on a Windows environment?

Cheers,

Mikael

**Comment by firojasha** [comment]
Thanks Mikael,  i am running this on Windows Environment and Module versions are ["serverless-kms-secrets": "^1.0.2",   "serverless": "^1.21.0"]

PLease let me know if any further information required.

Thanks,
Firoj Shaik

**Comment by mpuittinen** [comment]
@firojasha sls is an internal Powershell command (Select-string cmdlet), you need to use "serverless" (with the proper PATH set) instead.

**Comment by firojasha** [comment]
thanks @mpuittinen , Is there any way to pass multiple keys in single command line for encryption? **serverless encrypt -n company1 -v hello -k ******888***** ** , Rather running command multiple times for each key encryption ?

**Comment by mpuittinen** [comment]
Currently, you’ll need to run the command once for each secret. Alternatively, you can pack a set of sets into a JSON and store that with one single call, i.e.
serverless encrypt -n SECRETS -v ‘{“secret1:” “value1”, “secret2”, “value2”}’ -k *****

**Comment by firojasha** [comment]
if I dont want to show the value of encrypted key using the command  **serverless decrypt -n secret** for security concern, will that be possible ? please check this once.....

**Comment by mpuittinen** [comment]
What is the use case for running "serverless decrypt" but not wanting to see the secret?

**Comment by firojasha** [comment]
Yeah, if encrypt the key with the command **serverless encrypt -n company -v Google -k 5699 99999** then it is encrypted as **company: AQICAHg0kUSTdACAVYb6/vA/** , so if some one run the Decrypt command as **serverless decrypt -n company** this would result as **Google** this is not we needed to display the origial key value , so how to handle to not show the original key value with Decrypt command?

**Comment by mpuittinen** [comment]
The decrypt command is meant explicitly to decrypt the secret and show in plain text, i.e. that will not be changed. The decryption happens with the standard KMS API, i.e. if you want to limit a developers ability to decrypt the secrets, that would happen by limiting the permissions using AWS IAM.

**Comment by BharathRahulDS** [comment]
Is it not best to have the "Key" as a parameter to Decrypt any variable? that way we can restrict all users except for the valid users with the "Key" to decrypt. Also, to work in different environments, we should have multiple keys to ensure developers have all the access they need but on selected environment. Any thoughts?

**Comment by mpuittinen** [comment]
That is not how KMS works. First of all, the key given by -k during encryption is not the key, but the Id of the key stored in KMS. For decryption, the key parameter is not required since the key id is embedded within the encrypted secret. Access to encrypt / decrypt secrets is defined via IAM roles.
With the documented configuration, the serverless-kms-secrets plugin creates separate secret files based on the stage and region used. Other variables (e.g. AWS profile) can be used to form the secret file name. That way, the encrypted secrets for different envs (e.g. prod, dev) are stored in different files and can be encrypted using different KMS keys.
