### ISSUE TITLE
Numeric only key values return 413 unknown error

### ISSUE THREAD

**Issue by Replica-** [SC5/serverless-kms-secrets#6]
Running
sls encrypt -n XXXX_PASSWD -v 1234567 -k 9999-9999-9999-9999
Always results in
Serverless: UnknownError: 413

Alternatively, running
sls encrypt -n XXXX_PASSWD -v a1234567 -k 9999-9999-9999-9999
Results in success

Unfortunately, my XXXX_PASSWD is all Numeric characters. I would hazard a guess here - at some point the value is being interpreted as Number and not a String value.

**Comment by mpuittinen** [comment]
@Replica- Fixed in 0.9.6
