### ISSUE TITLE
Does not work with non-default profiles

### ISSUE THREAD

**Issue by kevinold** [SC5/serverless-kms-secrets#9]
I'm attempting to use with a non-default aws profile like so:

```
serverless encrypt --aws-profile sandbox -n TEST -v ABCD123 -k XXXXXXX9d-58d5-ZZZZ--AAAA-asdfasdfadf
```

I receive the following error:
```
Serverless: NotFoundException: Key 'arn:aws:kms:us-east-1:ZZZZZZZ:key/XXXXXXX-33333-44444-555-UUUUUUUU' does not exist
```

**Comment by mpuittinen** [comment]
Thanks @kevinold for reporting this. I've fixed the issue in the module version 0.9.7 but there is still one issue that relates to the Serverless framework. In case you define both AWS_PROFILE env var and --aws-profile cli option, the AWS_PROFILE is used. Intuitively, I'd consider that the cli option should have higher priority.

**Comment by mpuittinen** [comment]
Submitted PR to serverless : https://github.com/serverless/serverless/pull/3980

**Comment by mpuittinen** [comment]
@kevinold this should now work with serverless 1.21
